### ISSUE TITLE
询问报错原因

### ISSUE THREAD

**Issue by BoNing-Gu** [DertahSama/Paper_trans#1]
作者你好，我在运行TYPESEY.py这个文件时遇到了下面的报错，请问这个该如何解决？非常感谢！
`E:\PythonProject\paper_translate>D:/python/python.exe e:/PythonProject/paper_translate/Paper_translator-public/TYPESET.py
<< 请打开从Mathpix导出的tex文档...
>> 开始排版预处理...
标题: Text mining of news-headlines for FOREX market prediction: A Multi-layer Dimension Reduction Algorithm with semantics and sentiment 
作者：Arman Khadjeh Nassirtoussi \\,
Traceback (most recent call last):
  File "e:\PythonProject\paper_translate\Paper_translator-public\TYPESET.py", line 64, in <module>
    TYPESET(basedir,filename)
  File "e:\PythonProject\paper_translate\Paper_translator-public\TYPESET.py", line 48, in TYPESET
    tex_1 = lf.modify_table(tex_1,format_table)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\PythonProject\paper_translate\Paper_translator-public\typeset_func2.py", line 215, in modify_table
    title = line_title[t_idx:].strip()
            ^^^^^^^^^^
UnboundLocalError: cannot access local variable 't_idx' where it is not associated with a value`

这是我想要翻译的文件
[2024_02_25_2cefde743bc0c219ae21g.zip](https://github.com/DertahSama/Paper_translator/files/14396366/2024_02_25_2cefde743bc0c219ae21g.zip)

**Comment by DertahSama** [comment]
这是由于这里面的表格比较复杂，mathpix识别得到的代码比较乱，导致处理出错了吧……

这种情况可以直接把TYPESET.py里的 tex_1 = lf.modify_table(tex_1,format_table) 这行注释掉，即不处理表格，应该就能运行出来了。

鉴于表格内容的自由度太高，经常会出错，所以建议一直把这样注释掉，表格内容酌情人工处理，我现在就是这样用的

**Comment by BoNing-Gu** [comment]
ok！非常感谢！
